### ISSUE TITLE
Where are the downloaded files? Script not merging.

### ISSUE THREAD

**Issue by nullbert** [K-S-V/Scripts#35]
I downloaded the latest version of the script, fetched my manifest with the HDS LinkDetector, and ran the script. This is all that happened:

```
                            KSV Adobe HDS Downloader

Processing manifest info....
Quality Selection:
 Available: 2392 1413 713 387 213
 Selected : 2392
Fragments Total: 44, First: 1, Start: 1, Parallel: 8
Downloading 44/44 fragments
Found 44 fragments
Finished
```

As you can see, it says it downloads files, but I can't see any. Aren't they supposed to download to the same directory as the script?

**Comment by BrotherMaynerd** [comment]
I'm having the same issue. I can't find any .flv file on either system I'm trying to use this on.

One system is a HP Mini 110 running Linux Mint 17.1
One systems is a Windows 10 machine with PHP 5.4 installed.

The script displays the following information when executed:

Processing manifest info....
Quality Selection:
 Available: 1
 Selected: 1
Fragments Total: 331, First: 1, Start: 1, Parallel: 8
Downloading 331/331 fragments
Found 0 fragments
Finished


Nothing shows up anywhere, regardless of whether or not I use the --outdir --outfile commands.  The script does sequentially count through the fragments and does not finish instantaneously, so it seems as though it's receiving information, I just have no indication of where the file might be or the fragments.
