### ISSUE TITLE
Add copyright notices to header files

### ISSUE THREAD

**Issue by albsod** [K-S-V/Scripts#48]
Could you for each of the files please add copyright notices following this template (as recommended in the GPLv3 license text):

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

It's in my view important to add the part "either version 3 of the License, or (at your option) any later version" because the GPL may receive updates in the future that could be important to protect the freedom of users. Without that formulation present you are implicitly giving your scripts a "GPLv3 only" license.

**Comment by drzraf** [comment]
+1:
could you please state what the licence will be, so that it's known prior to do PR

**Comment by K-S-V** [comment]
it's GPL v3 as mentioned in [license file](https://github.com/K-S-V/Scripts/blob/master/License.txt).
