### ISSUE TITLE
AdobeHDS.php Parse error

### ISSUE THREAD

**Issue by mokrofuz** [K-S-V/Scripts#54]
Hello there, this is an error I am getting when I try to run php script locally:

Parse error: parse error, expecting `"identifier (T_STRING)"' in /Users/brani/Desktop/Again/AdobeHDS.php on line 23

I'm on OSX Maverick. Wrong php setup? Thanks a lot in advance...

**Comment by K-S-V** [comment]
Open the AdobeHDS.php file with any text editor and make sure the text displayed resembles the text displayed at following url:

https://raw.githubusercontent.com/K-S-V/Scripts/master/AdobeHDS.php
