### ISSUE TITLE
Flash and Akamai DRM Encryption

### ISSUE THREAD

**Issue by rmstxrx** [K-S-V/Scripts#55]
Hey, K-S-V.

I've been checking forums for a while and realized there haven't been any progress around Flash DRM and Akamai DRM encryption. Most people are just sticking to to the basics (a.k.a. finding alternate links), but there is no breakthrough in sight.

So, I'm just thinking about going in myself and trying something. Do you have any ideas? Any starting point? Did you ever try to break the encryption?

Thanks in advance.

**Comment by K-S-V** [comment]
I think you have missed [this] (url=http://stream-recorder.com/forum/showpost.php?p=59493&postcount=1) post. I haven't looked into it any further.
