### ISSUE TITLE
Fatel Error: mcrypt_module_open

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [K-S-V/Scripts#56]
Fatal error: Call to undefined function mcrypt_module_open() in AdobeHDS.php on line 362

this issue happens within the "Sep 11, 2015" version

when trying to download from:

php AdobeHDS.php --manifest "http://cbtnuggets-vh.akamaihd.net/z/fa/5e/fa5e91c5-b689-4277-b434-985ec4695ba3/acd5c4f16639a8c0a91b85aae5e157a16ae8ca18_10x_,150k,100k,400k,200k,500k,300k,.mp4.csmil/manifest.f4m?hdnea=st=1442298065~exp=1442305265~acl=/*~hmac=dbc55ce211da1bab7f76c0dab58c3296388e8b368c3633b9508eec06b07c3cdf&g=FRPNGBDVIERM&hdcore=3.3.0" --delete --auth "hdntl=exp=1442384651~acl=%2f*~data=hdntl~hmac=bfc8943da5e621dc11693b66eb60b32065ef3e9eb9aca4365a4b9613f59a658f&als=0,3,NaN,5,0,NaN,0,0,0,113,f,0,802.67,f,u,FRPNGBDVIERM,3.3.0,113&hdcore=3.3.0" --useragent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.1.0 Waterfox/38.1.0"

or any other CBT nugget video never had this issues with a previous version

**Comment by XxUnkn0wnxX** [comment]
the last working one is from: "major code refactoring to integrate new decryptor"
commit ca7772e8b08edda870f5ee7314df9ef28be88007

after that the Fatel error occurs when trying to download from CBTNuggets
please fix this..
i am also using the HDS Link Detector for firefox

**Comment by K-S-V** [comment]
New changes added the dependency on mcrypt module to decrypt the encrypted streams. you must install the php mcrypt module. if it's already installed make sure to enable it in your PHP.ini file. I will also add it to the required dependencies list in script.
