### ISSUE TITLE
Resuming After Failure

### ISSUE THREAD

**Issue by AksharCodes** [K-S-V/Scripts#63]
I have downloaded 152 fragments and it failed. How to resume fragments from 152 and assemble all the fragments in one file. I have used --start option but it creates new file and does not consider previously downloaded segments. 
```
                            KSV Adobe HDS Downloader

Processing manifest info....                                                   
Quality Selection:                                                             
 Available: 2061 1361 861 461 241
 Selected : 861                                                                
Fragments Total: 207, First: 1, Start: 1, Parallel: 1                          
SessionKey: 5630021d0b6d8c16254b5e7bac908d2d                                   
Failed to download akamai session decryption key
```

**Comment by K-S-V** [comment]
Normally it auto-detects the previously downloaded fragment files and uses them instead of downloading from server. can you provide the command line you are using?

**Comment by hmemar** [comment]
Thats when you clear packages 
Clear cache
And restart kosi

Regards

Husham Memar

**Comment by AksharCodes** [comment]
@K-S-V 
I am using the following command provided by HDS Link Detector.

php AdobeHDS.php --manifest "http://staragvod1-vh.akamaihd.net/z/videos/plus/skr/28/1000079513_,180,400,800,1300,2000,_STAR.mp4.csmil/manifest.f4m?hdnea=st=1451694668~exp=1451695268~acl=/*~hmac=e7882234a647574db0df8e5b146d6a73fcbb6251c6f24fe42f2541495412a212&g=UHFKBVIPZDEK&hdcore=3.7.0&plugin=aasp-3.7.0.39.44" --delete --quality low --parallel 1 --auth "hdntl=exp=1451781371~acl=%2f*~data=hdntl~hmac=4b7c65093dafa888a1cdc87108232a2e039942134c773f8b1e72c977d548a884&als=0,3,NaN,4,0,NaN,0,0,0,35,f,0,1288.52,f,u,UHFKBVIPZDEK,3.7.0,35&hdcore=3.7.0&plugin=aasp-3.7.0.39.44" --useragent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0"

**Comment by K-S-V** [comment]
There may be alternative streams available but this repository isn't suitable place to talk about that. if you have the corresponding session key then you can decrypt those fragments (using --adkey switch) otherwise only option is to re-download the stream.

**Comment by AksharCodes** [comment]
I have figured out how to get similar functionality to resume but I don't know the command to join two files. I can use --start option to start from the required fragment. But now I have two FLV files, can you just give me a PHP script for joining two FLV files?
