### ISSUE TITLE
how to use the quality [PARAM]

### ISSUE THREAD

**Issue by torai** [K-S-V/Scripts#64]
hello , please could you provide the correct line in which I can select the quality because I tried many combinations I got errors in all of them 

```
php AdobeHDS.php --quality [medium]
```

when I modified the quality inside the PHP file the grabber stuck in this 

```
Processing manifest info....
Quality Selection:
 Available: 5056 2104 1297 764 459 256
 Selected : 2104
Fragments Total: 182, First: 181, Start: 181, Parallel: 8
Downloading 181/182 fragments
```

 nothing happened next it stays like this

**Comment by AksharCodes** [comment]
you can use any one of low,medium and high as follows:

php AdobeHDS.php --quality low

you can also select quality from list of available:

php AdobeHDS.php --quality 764

**Comment by torai** [comment]
already figured out in teh main PHP file bro , is there any chance to capture RTMP with this tool or some other tools ( php based as well ) ?
