### ISSUE TITLE
Add Option to Join Two FLV files

### ISSUE THREAD

**Issue by akshar26** [K-S-V/Scripts#66]
Please add --join option to join two FLV files. This will work exactly as resume feature. 
You already have the code to join multiple fragments, so implementing of joining two FLV files would not take much time.

**Comment by K-S-V** [comment]
You already have two options in this case.

1. you can use ffmpeg to join those files. https://trac.ffmpeg.org/wiki/Concatenate

2. You can strip the flv header (first 13 bytes) from all other files except the first one and then join all the parts using copy command.

```
copy /b 1.flv+2.flv+3.flv joined.flv
```

After that to fix the timestamps you can use the FlvFixer.php script available in this repository.

```
php FLVFixer.php -in "joined.flv" -out "final.flv" -nometa
```
