### ISSUE TITLE
Redeclaration of function ReadString()

### ISSUE THREAD

**Issue by blu-jabr** [K-S-V/Scripts#67]
I just discovered AdobeHDS.php this evening, but when I tried to use it, it failed due to the 
function ReadString() being redefined:

PHP Fatal error:  Cannot redeclare ReadString() in /home/jabr/Scripts-master/AdobeHDS.php on line 1660

I figured "ReadString" was probably already built into php, so I edited AdobeHDS.php and globally replaced "ReadString" with "MyReadString". After doing this, the script worked fine.

I'm running this on a Linux system, specifically CentOS 6.7. PHP version is 5.3.3.

**Comment by K-S-V** [comment]
php doesn't have any such function. it may be something else (another extension?) in your environment redeclaring that function in global scope.
