### ISSUE TITLE
New encrypted Akamai 

### ISSUE THREAD

**Issue by cesarDevOp** [K-S-V/Scripts#68]
Hi
In a website, i use AdobeHDS.php with no problems to download the video, but in the same website there are new videos that this command says "Access Denied! Unable to download the manifest".

The diference between these two videos is the url, which include the string ENC ( encryptation i think). Here is an example:

works:
```
--manifest "http://mitele1-vh.akamaihd.net/z/geo/tc/wp/tcwp124ne1G6GPoENU6zW3/srMEmXPdurCgVccEOKs4o1.1100,,.mp4.csmil/manifest.f4m?......
```
not works:
```
--manifest "http://mitele1-vh.akamaihd.net/z/enc/geo/cd/qG/cdqGyhD6ZBuGF2mCtRl5P4/3c3l6JQY3DCcqt889qQ924.1100,,.mp4.csmil/manifest.f4m?....
```

**Comment by K-S-V** [comment]
This is not related to Akamai Media Encryption in any way. most probably manifest authentication token is expired by the time you are trying to use it. some websites use extremely short lived authentication tokens (10 seconds or even less).
