### ISSUE TITLE
This stream is encrypted with FlashAccess DRM (2016)

### ISSUE THREAD

**Issue by ryanf86** [K-S-V/Scripts#70]
So here is the problem. Which actually has me a little confused.

I'm trying to download the video from this link: 
https://au.tv.yahoo.com/plus7/cats-make-you-laugh-out-loud/-/watch/30572055/cats-make-you-laugh-out-loud-thu-14-jan-season-1-episode-2/

Now i have no issue downloading the above video using the scripts here:
https://github.com/blha303/plus7-tools

But when i try to use the AdobeHDS.php I get the following error:

```
                            KSV Adobe HDS Downloader

Processing manifest info....                                                   
Quality Selection:                                                             
 Available: 1619 1320 992 695 339
 Selected : 1619                                                               
Fragments Total: 447, First: 1, Start: 1, Parallel: 8                          
This stream is encrypted with FlashAccess DRM. Decryption of such streams isn't currently possible with this script.
```
Is anyone able to test and replicate the issue that i'm having? And if so is there something in the scripts that work to download the video that could perhaps be added into the AdobeHDS.php to make it work?

**Comment by K-S-V** [comment]
It's quite possible that other program you mentioned is downloading the video using alternative streams available (HLS [.m3u8])  instead of using HDS.
