### ISSUE TITLE
wmv filetype 

### ISSUE THREAD

**Issue by torai** [K-S-V/Scripts#75]
hello how to download the wmv using this it's on http & mms ; 

I used the ordinary script line but it didn't work , any tip or trick could help me with ? 

thanks 

( HDS link detector didn't detect the WMV file only MP4 )

**Comment by K-S-V** [comment]
If you are talking about AdobeHDS script then this script only supports Adobe HDS protocol. for mms there are plenty of other tools available on the internet.
