### ISSUE TITLE
only 4 fragments found ? ( please read ) 

### ISSUE THREAD

**Issue by torai** [K-S-V/Scripts#76]
hello , how to fix this ? 

http://i.imgur.com/h5aeOp9.png

1350 fragments only 4 found 

also the download is so fast

**Comment by K-S-V** [comment]
Add the following switch to your command line and you may get the reason of failure. most probably server don't have all the fragments listed in manifest file. it may happen with live streams where only last few fragments remain accessible when live stream is finished.

```
--debug 2> Debug.txt
```

**Comment by torai** [comment]
it's fixed now it's there , ( the problem was that the video was only for streaming not download ) , but the flv file won't split or work with avidemux is there any trick to download directly MP4 file ?

**Comment by d3ibis** [comment]
@torai Try to convert it using ffmpeg (using -c copy) to copy all settings of codec & try
