### ISSUE TITLE
FlashAccess DRM?

### ISSUE THREAD

**Issue by joejones14** [K-S-V/Scripts#80]
Was using this script successfully for awhile, then all of the sudden I get this message about FlashAccess DRM.  Any solutions?

http://i.imgur.com/6KFgtyP.png

**Comment by K-S-V** [comment]
Your target site may have recently switched to **FlashAccess DRM**. AFAIK there is no public solution available for that DRM.

**Comment by joejones14** [comment]
Thanks for the response K-S-V, FlashAccess DRM has proven to be uncrackable so far.
