### ISSUE TITLE
Feature Request: Multiple Qualities

### ISSUE THREAD

**Issue by MrPaulAR** [K-S-V/Scripts#84]
This would be useful for sites that provide different audio & video streams.  Ability to join the 2 streams into 1 file would be nice but not as important.

**Comment by albino1** [comment]
+1

Having to do each one separately seems unnecessary, and yeah having them combine automatically would obviously be a good secondary addition to that.

**Comment by K-S-V** [comment]
Very few websites out there serve separate audio and video streams via HDS. your best bet in that scenario is to use two different console windows to download audio and video stream simultaneously using the same link. adding post processing for downloaded streams isn't something I am willing to add.

**Comment by albino1** [comment]
Understandable.  I solved it with a little batch script anyway.  Thanks for the reply!
