### ISSUE TITLE
'Failed to write flv data to file' after filesize reaches 2 GB (AdobeHDS)

### ISSUE THREAD

**Issue by dftsf** [K-S-V/Scripts#85]
Hi

I'm trying to download HDS stream,
but when flv filesize reaches 2 GB on my HDD
script stops with a 'Failed to write flv data to file' error.

I've only got this problem now when I switched to Manjaro (Arch Linux derivative),
I never had this error previously with AdobeHDS.php on Windows and Ubuntu.

Thanks.

**Comment by K-S-V** [comment]
it seems like you are using very old version of PHP. try to update your PHP installation.
