### ISSUE TITLE
fixwindow and timeshift

### ISSUE THREAD

**Issue by xlhdh** [K-S-V/Scripts#87]
What is a timeshift, and how should I use the --fixwindow parameter in AdobeHDS.php? 
Thank you so much!

**Comment by K-S-V** [comment]
it's used internally by the AdobeHDS.php script to fix the timestamps of decoded fragments. it's useful when the provided timestamps are not sequential (e.g. missing fragments) or negative. unless you are having any issue with decoded timestamp you won't need to use **--fixwindow** parameter.
